### ISSUE TITLE
Inspector - Not Operational

### ISSUE THREAD

**Issue by bkthomson** [mtgatracker/mtgatracker#489]
[mtga_watch.log](https://github.com/mtgatracker/mtgatracker/files/2749975/mtga_watch.log)

I pulled fresh code 5.0.5 and after sever game i try to view the Insepector data and no content appears.  The inspector window opens correctly but the main content pane is empty.  The left menu pane shows the correct items (Home, Profile, etc)  

One item stands out. the "Hello," message reads "Hello, {data.username}"

Anytime I select a menu items from the left pane the window refreshes to just a white screen.  No Matter how long I wait no content appears.  

I've attached the latest watch_log for review that does show quite a few errors within today session using the application.

**Comment by andreasjacobsen93** [comment]
I have the same problem.

I get the following error in the console:
```
Uncaught ReferenceError: page is not defined
    at HTMLDocument.<anonymous> (C:\Users\***\AppData\Local\mtgatracker\app-5.1.0\resources\app.asar\inspector\js\spaRouter.js:39:5)
    at l (C:\Users\***\AppData\Local\mtgatracker\app-5.1.0\resources\app.asar\jquery.js:2:29375)
    at c (C:\Users\***\AppData\Local\mtgatracker\app-5.1.0\resources\app.asar\jquery.js:2:29677)
```
